---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integrationmanagement
  description: Microservicios para la persistencia y administración de la bitácora de procesos/Servicios para registrar y consultar la bitácora desde cualquier subetapa de los trámites y los servicios para la generación y persistencia de los folios.
  tags:
    - microservice
    - logging
  links:
    - url: https://github.com/JCAL0199/Integrationmanagement
      title: Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    endpoints/dev: https://api.dev.company1.mx/company/1/nci-bdnsarintegrationmanagement
    endpoints/qa: https://api.qa.company1.mx/company/1/nci-bdnsarintegrationmanagement
    endpoints/prod: https://api.company1.mx/company/1/nci-bdnsarintegrationmanagement
spec:
  type: service
  owner: group:default/juan-manuel-perez
  lifecycle: production
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  description: Dispersión Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/service-flask
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  description: Dispersión Ordinaria IMSS/Carga Archivo -Edición
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  description: Dispersión Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
